export default {
	TYPE_INTERACTION: "interaction",
	TYPE_INTERACTION_NEGATION: "interaction_negation",
	TYPE_TIME_DISTANCE: "time_distance",
	TYPE_DURATION: "duration",
	TYPE_OR_INTERACTION: "interaction-or",
	TYPE_TEMPORAL: "temporal",
	MSG_AXIOM_CREATION_DONE: "axiom-creation-done",
	MSG_CREATE_NEW_AXIOM: "create-new-axiom",
	MSG_TIME_CONSTRAINT_UPDATED: "time-constraint-updated",
	MSG_TIME_CONSTRAINT_STATUS_UPDATED: "time-constraint-status-updated",
	MSG_ADD_ACTIVITY: "add_activity",
	MSG_REMOVE_ACTIVITY: "remove_activity",
	MSG_CHANGE_CURRENT_ACTIVITY: "change_current_activity",
	MSG_ACTIVITY_TITLE_UPDATING: "activtity_title_updating",
	MSG_ACTIVITY_TITLE_UPDATED: "activtity_title_updated",
	MSG_TIME_CONSTRAINT_FINALIZED: "time_constraint_finalized",
	MSG_CLASSIFY_CURRENT_INSTANCE: "classify_current_instance",
	MSG_REMOVE_OBJECT_INTERACTION: "remove_object_interaction",
	MSG_REMOVE_OBJECT_INTERACTION_EXCLUSION: "remove_object_interaction_exclusion",
	MSG_INTERACTION_OR_AXIOM_CREATION: "interaction-or-axiom-creation",
	MSG_TIME_DISTANCE_AXIOM_FLIP_EVENTS: "time-distance-axiom-flip-events",
	MSG_REMOVE_AXIOM: "remove_axiom",
	VALUE_DEFAULT_TH1: 10,
	VALUE_DEFAULT_TH2: 20,
	AX_CHANGE_LIMIT_EXPANTION: "ax_change_limit_expantion",
	AX_CHANGE_TEMPORAL_REMOVAL: "ax_change_temporal_removal",
};
